name: Case study with Docker

on: [push]
jobs:
  build-and-generate-report:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./case-study/docker

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Build the Docker image
        # This step runs the Dockerfile, which includes the 'make all' command.
        # When this step is complete, the report is already generated inside the image.
        run: docker build -t rbc-pipeline-image .

      - name: Extract the report from the Docker image
        # We don't need to 'docker run' the whole pipeline again.
        # We can create a temporary container and copy the finished report out.
        run: |
          # Create a directory on the runner to hold the report.
          mkdir -p ./report-output

          # Create a temporary, non-running container from our image.
          id=$(docker create rbc-pipeline-image)

          # Copy the generated HTML report from the container's filesystem
          # to the directory we just created on the runner.
          docker cp ${id}:/rbc/report/readme.html ./report-output/readme.html

          # Clean up the temporary container.
          docker rm -v ${id}

      - name: Upload the report as an artifact
        uses: actions/upload-artifact@v5
        with:
          name: rbc-model-report
          path: ./report-output/readme.html
