name: Run Repro Script
on: [push]
jobs:
  run-reproducible-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=https://github.com/rstats-on-nix/nixpkgs/archive/refs/heads/r-daily.tar.gz

      - uses: cachix/cachix-action@v14
        with:
          name: rstats-on-nix

      - name: Run the pipeline and record execution time
        # The working-directory is set to the folder containing your script.
        working-directory: ./repro-script
        run: |
          # Record the start time using a Unix timestamp.
          start_time=$(date +%s)
          # Make the script executable and run it.
          # The script will create all necessary files and execute the Nix pipeline.
          chmod +x ./repro_script.sh
          ./repro_script.sh
          # Record the end time and calculate the total duration.
          end_time=$(date +%s)
          duration=$((end_time - start_time))

          # Format the duration into minutes and seconds for readability.
          minutes=$((duration / 60))
          seconds=$((duration % 60))
          # Append a formatted message to the GitHub Actions summary view.
          # This makes the total runtime prominently visible in the UI.
          if [ -n $GITHUB_STEP_SUMMARY ]; then
            echo "### ⏱️ Pipeline Execution Time" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "The reproducible pipeline finished in **$minutes minute(s) and $seconds second(s)**." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "The final report is available at \`final_report/readme.html\` in the runner." >> $GITHUB_STEP_SUMMARY
          else
            echo "Pipeline execution time: $minutes minute(s) and $seconds second(s)"
          fi
